/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/public_details": {
    get: {
      parameters: {
        query: {
          bio?: parameters["rowFilter.public_details.bio"];
          id?: parameters["rowFilter.public_details.id"];
          first_name?: parameters["rowFilter.public_details.first_name"];
          last_name?: parameters["rowFilter.public_details.last_name"];
          image_url?: parameters["rowFilter.public_details.image_url"];
          role?: parameters["rowFilter.public_details.role"];
          country?: parameters["rowFilter.public_details.country"];
          city?: parameters["rowFilter.public_details.city"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["public_details"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** public_details */
          public_details?: definitions["public_details"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          bio?: parameters["rowFilter.public_details.bio"];
          id?: parameters["rowFilter.public_details.id"];
          first_name?: parameters["rowFilter.public_details.first_name"];
          last_name?: parameters["rowFilter.public_details.last_name"];
          image_url?: parameters["rowFilter.public_details.image_url"];
          role?: parameters["rowFilter.public_details.role"];
          country?: parameters["rowFilter.public_details.country"];
          city?: parameters["rowFilter.public_details.city"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          bio?: parameters["rowFilter.public_details.bio"];
          id?: parameters["rowFilter.public_details.id"];
          first_name?: parameters["rowFilter.public_details.first_name"];
          last_name?: parameters["rowFilter.public_details.last_name"];
          image_url?: parameters["rowFilter.public_details.image_url"];
          role?: parameters["rowFilter.public_details.role"];
          country?: parameters["rowFilter.public_details.country"];
          city?: parameters["rowFilter.public_details.city"];
        };
        body: {
          /** public_details */
          public_details?: definitions["public_details"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/events": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          created_at?: parameters["rowFilter.events.created_at"];
          start_date_time?: parameters["rowFilter.events.start_date_time"];
          end_date_time?: parameters["rowFilter.events.end_date_time"];
          owner?: parameters["rowFilter.events.owner"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["events"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** events */
          events?: definitions["events"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          created_at?: parameters["rowFilter.events.created_at"];
          start_date_time?: parameters["rowFilter.events.start_date_time"];
          end_date_time?: parameters["rowFilter.events.end_date_time"];
          owner?: parameters["rowFilter.events.owner"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.events.id"];
          created_at?: parameters["rowFilter.events.created_at"];
          start_date_time?: parameters["rowFilter.events.start_date_time"];
          end_date_time?: parameters["rowFilter.events.end_date_time"];
          owner?: parameters["rowFilter.events.owner"];
        };
        body: {
          /** events */
          events?: definitions["events"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/notification_token": {
    get: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.notification_token.created_at"];
          token?: parameters["rowFilter.notification_token.token"];
          created_by?: parameters["rowFilter.notification_token.created_by"];
          name?: parameters["rowFilter.notification_token.name"];
          device_id?: parameters["rowFilter.notification_token.device_id"];
          id?: parameters["rowFilter.notification_token.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["notification_token"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** notification_token */
          notification_token?: definitions["notification_token"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.notification_token.created_at"];
          token?: parameters["rowFilter.notification_token.token"];
          created_by?: parameters["rowFilter.notification_token.created_by"];
          name?: parameters["rowFilter.notification_token.name"];
          device_id?: parameters["rowFilter.notification_token.device_id"];
          id?: parameters["rowFilter.notification_token.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.notification_token.created_at"];
          token?: parameters["rowFilter.notification_token.token"];
          created_by?: parameters["rowFilter.notification_token.created_by"];
          name?: parameters["rowFilter.notification_token.name"];
          device_id?: parameters["rowFilter.notification_token.device_id"];
          id?: parameters["rowFilter.notification_token.id"];
        };
        body: {
          /** notification_token */
          notification_token?: definitions["notification_token"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          first_name?: parameters["rowFilter.users.first_name"];
          last_name?: parameters["rowFilter.users.last_name"];
          email?: parameters["rowFilter.users.email"];
          image_url?: parameters["rowFilter.users.image_url"];
          role?: parameters["rowFilter.users.role"];
          dob?: parameters["rowFilter.users.dob"];
          country?: parameters["rowFilter.users.country"];
          city?: parameters["rowFilter.users.city"];
          enableNotifications?: parameters["rowFilter.users.enableNotifications"];
          optForNewsletters?: parameters["rowFilter.users.optForNewsletters"];
          legalAccepted?: parameters["rowFilter.users.legalAccepted"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          first_name?: parameters["rowFilter.users.first_name"];
          last_name?: parameters["rowFilter.users.last_name"];
          email?: parameters["rowFilter.users.email"];
          image_url?: parameters["rowFilter.users.image_url"];
          role?: parameters["rowFilter.users.role"];
          dob?: parameters["rowFilter.users.dob"];
          country?: parameters["rowFilter.users.country"];
          city?: parameters["rowFilter.users.city"];
          enableNotifications?: parameters["rowFilter.users.enableNotifications"];
          optForNewsletters?: parameters["rowFilter.users.optForNewsletters"];
          legalAccepted?: parameters["rowFilter.users.legalAccepted"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          first_name?: parameters["rowFilter.users.first_name"];
          last_name?: parameters["rowFilter.users.last_name"];
          email?: parameters["rowFilter.users.email"];
          image_url?: parameters["rowFilter.users.image_url"];
          role?: parameters["rowFilter.users.role"];
          dob?: parameters["rowFilter.users.dob"];
          country?: parameters["rowFilter.users.country"];
          city?: parameters["rowFilter.users.city"];
          enableNotifications?: parameters["rowFilter.users.enableNotifications"];
          optForNewsletters?: parameters["rowFilter.users.optForNewsletters"];
          legalAccepted?: parameters["rowFilter.users.legalAccepted"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/news": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.news.id"];
          created_at?: parameters["rowFilter.news.created_at"];
          title?: parameters["rowFilter.news.title"];
          description?: parameters["rowFilter.news.description"];
          category?: parameters["rowFilter.news.category"];
          img?: parameters["rowFilter.news.img"];
          link?: parameters["rowFilter.news.link"];
          author_name?: parameters["rowFilter.news.author_name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["news"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** news */
          news?: definitions["news"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.news.id"];
          created_at?: parameters["rowFilter.news.created_at"];
          title?: parameters["rowFilter.news.title"];
          description?: parameters["rowFilter.news.description"];
          category?: parameters["rowFilter.news.category"];
          img?: parameters["rowFilter.news.img"];
          link?: parameters["rowFilter.news.link"];
          author_name?: parameters["rowFilter.news.author_name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.news.id"];
          created_at?: parameters["rowFilter.news.created_at"];
          title?: parameters["rowFilter.news.title"];
          description?: parameters["rowFilter.news.description"];
          category?: parameters["rowFilter.news.category"];
          img?: parameters["rowFilter.news.img"];
          link?: parameters["rowFilter.news.link"];
          author_name?: parameters["rowFilter.news.author_name"];
        };
        body: {
          /** news */
          news?: definitions["news"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  public_details: {
    /** Format: text */
    bio?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    id: string;
    /** Format: text */
    first_name?: string;
    /** Format: text */
    last_name?: string;
    /** Format: text */
    image_url?: string;
    /**
     * Format: text
     * @default user
     */
    role: string;
    /** Format: text */
    country?: string;
    /** Format: text */
    city?: string;
  };
  events: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    start_date_time: string;
    /** Format: timestamp with time zone */
    end_date_time: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `public_details.id`.<fk table='public_details' column='id'/>
     */
    owner: string;
  };
  notification_token: {
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    token: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    created_by: string;
    /**
     * Format: character varying
     * @default unknow
     */
    name: string;
    /** Format: character varying */
    device_id?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
  };
  users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    first_name: string;
    /** Format: text */
    last_name: string;
    /** Format: text */
    email: string;
    /** Format: text */
    image_url?: string;
    /**
     * Format: text
     * @default user
     */
    role: string;
    /** Format: date */
    dob?: string;
    /** Format: text */
    country?: string;
    /** Format: text */
    city?: string;
    /**
     * Format: boolean
     * @default false
     */
    enableNotifications: boolean;
    /**
     * Format: boolean
     * @default false
     */
    optForNewsletters: boolean;
    /**
     * Format: boolean
     * @default false
     */
    legalAccepted: boolean;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  /** @description add news display on homepage */
  news: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: character varying */
    title?: string;
    /** Format: text */
    description?: string;
    /**
     * Format: public.news_categ
     * @enum {string}
     */
    category?: "game" | "sleep" | "news";
    /** Format: character varying */
    img?: string;
    /** Format: character varying */
    link?: string;
    /** Format: character varying */
    author_name?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description public_details */
  "body.public_details": definitions["public_details"];
  /** Format: text */
  "rowFilter.public_details.bio": string;
  /** Format: uuid */
  "rowFilter.public_details.id": string;
  /** Format: text */
  "rowFilter.public_details.first_name": string;
  /** Format: text */
  "rowFilter.public_details.last_name": string;
  /** Format: text */
  "rowFilter.public_details.image_url": string;
  /** Format: text */
  "rowFilter.public_details.role": string;
  /** Format: text */
  "rowFilter.public_details.country": string;
  /** Format: text */
  "rowFilter.public_details.city": string;
  /** @description events */
  "body.events": definitions["events"];
  /** Format: bigint */
  "rowFilter.events.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.events.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.events.start_date_time": string;
  /** Format: timestamp with time zone */
  "rowFilter.events.end_date_time": string;
  /** Format: uuid */
  "rowFilter.events.owner": string;
  /** @description notification_token */
  "body.notification_token": definitions["notification_token"];
  /** Format: timestamp with time zone */
  "rowFilter.notification_token.created_at": string;
  /** Format: text */
  "rowFilter.notification_token.token": string;
  /** Format: uuid */
  "rowFilter.notification_token.created_by": string;
  /** Format: character varying */
  "rowFilter.notification_token.name": string;
  /** Format: character varying */
  "rowFilter.notification_token.device_id": string;
  /** Format: uuid */
  "rowFilter.notification_token.id": string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: text */
  "rowFilter.users.first_name": string;
  /** Format: text */
  "rowFilter.users.last_name": string;
  /** Format: text */
  "rowFilter.users.email": string;
  /** Format: text */
  "rowFilter.users.image_url": string;
  /** Format: text */
  "rowFilter.users.role": string;
  /** Format: date */
  "rowFilter.users.dob": string;
  /** Format: text */
  "rowFilter.users.country": string;
  /** Format: text */
  "rowFilter.users.city": string;
  /** Format: boolean */
  "rowFilter.users.enableNotifications": string;
  /** Format: boolean */
  "rowFilter.users.optForNewsletters": string;
  /** Format: boolean */
  "rowFilter.users.legalAccepted": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.updated_at": string;
  /** @description news */
  "body.news": definitions["news"];
  /** Format: bigint */
  "rowFilter.news.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.news.created_at": string;
  /** Format: character varying */
  "rowFilter.news.title": string;
  /** Format: text */
  "rowFilter.news.description": string;
  /** Format: public.news_categ */
  "rowFilter.news.category": string;
  /** Format: character varying */
  "rowFilter.news.img": string;
  /** Format: character varying */
  "rowFilter.news.link": string;
  /** Format: character varying */
  "rowFilter.news.author_name": string;
}

export interface operations {}

export interface external {}
